### PR TITLE
Update tests to work with Ember protocol

### PR DESCRIPTION
**Pull request by bendemboski**

### CODE REVIEW

**Comment by pichfl** [comment]
I was wondering: Could we move the protocol to a generic location and use for both app and tests?

**Comment by bendemboski** [comment]
You're addressing the fact that the file shows up in two places in the addon -- once in the blueprint and once in `/ember-electron`? That's because the addon is acting both as an addon that needs to have the file in the blueprint to install in host apps, and also as an application so we can run `ember electron:test` in the addon, meaning that we need to make it kinda look like we ran `ember-electron`'s blueprint on the addon itself so it looks enough like an ember electron-enabled app to run `ember electron:test`.

So, the file is duplicated in this addon, but in applications using this addon, the blueprint would just create the file in one place, and that file would be used for both app and tests.

I see several options here:

1. Leave it as-is, and embrace the less-than-ideal state of having the file in two places so it has to be updated in two places whenever we change it (which is the same for `tests/electron.js`).
2. Leave it as-is, but play a little trick in the addon itself. So instead of `ember-electron/protocol-ember.js` being a copy of `blueprints/ember-electron/files/ember-electron/protocol-ember.js`, it would just re-export it as a module, so its content would be `module.exports = require('../blueprints/ember-electron/files/ember-electron/protocol-ember.js`).
3. Instead of putting `protocol-ember.js` in the blueprint, just put it in the `ember-electron` addon somewhere and import it from there. That means that `ember-electron/electron.js` would import `ember-electron/protocol-ember.js` (or `ember-electron/lib/protocol-ember.js` or something) instead of `./protocol-ember.js`. The problem is that since `protocol-ember.js` is needed at runtime, application would have to install `ember-electron` as a `dependency` instead of a `devDependency`, which I think would cause the entire addon and its dependencies to be packaged up when running `electron:package` or `electron:make`, which I really don't think we want!
4. Create a separate `electron-protocol-ember` (or maybe make it more generic and call it `ember-electron-runtime`) library that is a `devDependency` of `ember-electron` (so `ember-electron`'s tests can run against it), and that `ember-electron`'s blueprint installs into the host app (so the app can run against it in testing/dev and packaged mode).

I agree that (1) kinda sucks. I think (3) is a non-starter because of how it would bloat packaged apps with tons of extra dependencies just for this one file. (4) is probably the most architecturally "correct" solution, but maybe seems like maybe overkill for just one or two files? So maybe (2) is best for now, even though it seems kinda dubious importing files from the blueprint (but I can't think of any practical reason not to do it).

**Comment by pichfl** [comment]
I had something similar to (2) in mind. Do you have time to include this here? If not I'll merge this and continue on my own 🙂

**Comment by bendemboski** [comment]
Hmm...I'm kind of stymied on how to actually do (2). The problem is that it gets imported at runtime when our cwd and all the javascript files are off in a temp directory somewhere, and I'm not sure how to find the root of the ember project and the blueprints directory from there...

**Comment by pichfl** [comment]
Turns out we could use a similar protocol in a non ember project anyway, therefore I'm currently preparing everything for a very generic version of (4).

**Pull request merged**
